version: '2'
services:
  upload-db:
    image: mysql
    ports:
      - "3304:3304"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arqsoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: upload
      MYSQL_HOST: upload-db
  upload-ms:
    build: .
    # image: djguzmanc/upload_ms
    command: bash -c "sleep 100 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3002 -b '0.0.0.0'"
    ports: 
      - "3002:3002"
    depends_on: 
      - upload-db